project:
  type: book

book:
  title: "Applied Business Research"
  author: "Eric Weisbrod, with collaboration from ACCT 995 Students"
  date: "1/22/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - project-setup.qmd
    - global-params-packs-util.qmd
    - obtain-data.qmd
    - merge-data.qmd
    - visualizations.qmd
    - regression-table.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: spacelab

