# Merging Data (In Progress)

This chapter will go over how to merge in data from various sources. This will include examples of how to merge in firm-level data from various sources, and time-series data from FRED/Fama-French Factors/CRSP Index Files.

## Common Sources of Firm-Level Data

Below is a table of common sources and firm identifiers that allow researchers to link data from different data sources:

| Data Source | Identifiers | Other Firm Identifiers | Can Be Linked To | Notes |
|----|:--:|:--:|:--:|:---|
| **Compustat** | GVKEY | Ticker, CIK | CRSP, Audit Analytics |  |
| **CRSP** | PERMNO | Ticker, CUSIP | Compustat, IBES | To link to Compustat data, researchers should use the CRSP-Compustat link file for PERMNO-GVKEY mapping. |
| **I/B/E/S** | TICKER | OFTIC, CUSIP | CRSP | The "TICKER" variable is the I/B/E/S firm identifier **not** the trading symbol. The trading symbol is the "OFTIC" variable. |
| **TAQ** | SYMBOL |  |  |  |
| **TRACE** | CUSIP |  | CRSP |  |
| **Audit Analytics** | CIK |  | Compustat |  |
| **XBRL** | CIK |  | Compustat |  |
| **RavenPack** | RP_ENTITY_ID | CUSIP | CRSP, IBES |  |

Blocking out for next attempt
